% LEMming_Slicer.m - a collection of useful commands for plotting
% topography generated by LEMming and extracting profiles.

% Manually load an output file first...

clc
%close all

ncontours = 3;
cinterval = cinterval * 2;
colordef white

% % Original plots
% stype = (RTGrid .* (z_max_plot / numStypes)) + (topo/numStypes);
% figure(10); clf; colormap jet; contour3(Xs,Ys,topo,cinterval:cinterval:z_max_plot,'k'); hold on; surfc(Xs,Ys,topo,stype); set(gca,'DataAspectRatio',[1 1 1/VE]); view(-50,50); zlim([z_bound z_max_plot]); shading interp;
% title([run_name ' Topography and Lithology, Year ' int2str(t)]);

% regmap = Regolith_H; 
% RegHCutoff = min( max(max(Regolith_H)), 20 );
% %regmap(AccGrid > 10*dx*dy) = 256;
% figure(11); clf; colormap jet; contour3(Xs,Ys,topo,cinterval:cinterval:z_max_plot,'k'); hold on; caxis([min(min(Regolith_H)) RegHCutoff]); surfc(Xs,Ys,topo,regmap); colorbar; set(gca,'DataAspectRatio',[1 1 1/VE]); view(-50,50); zlim([z_bound z_max_plot]); shading interp;
% title([run_name ' Regolith Thickness (m), Year ' int2str(t)]);
% 
% topof = flipud(topo);
% 
% figure(1)
% % 
% % colormap('Gray')
% % imagesc(topof)
% % hold on
% % contour(topof,[450 450],'k')
% % % hold on
% % % contour(topof,ncontours/2,'k','linewidth',2)
% % axis image
% 
swathpos = 70;
swathwidth = 20;

swath = mean(topo(:,swathpos:swathpos+swathwidth),2);

figure(3)
clf
plot(Ys,swath,'k','linewidth',2)
axis image
hold on
% 
% cliffedge = input('Where is the cliff edge? (m) > ');
% 
% cliffedgepos = y-(cliffedge/10);
% 
% figure(3)
% cliffbase = input('Where is the plinth base? (m) > ');
% 
% cliffbasepos = y-(cliffbase/10);
% 
% plinthlength = cliffbasepos-cliffedgepos;
% nmidprofiles = 5;   % number of profiles to draw between top and bottom of plinth
% profspace = round(plinthlength/nmidprofiles);
% 
% figure(2)
% clf
% plot(Xs,topof(cliffedgepos-25,:),'k','linewidth',2)
% hold on
% 
% for ip = cliffedgepos:profspace:cliffbasepos
%     plot(Xs,topof(ip,:),'k')
%     hold on
% end
% 
% plot(Xs,topof(cliffbasepos+25,:),'k','linewidth',2)
% axis image
% % 
% isRF = RF_Debris_H > 0;
% 
% pctDebrisCover = sum(sum(isRF)) / (x*y) %#ok<NOPTS>
% plinthDebrisCover = sum(sum(isRF(cliffedgepos:cliffbasepos,:))) / (x*plinthlength) %#ok<NOPTS>
% plinthDist = plinthlength * 10 %#ok<NOPTS>
% plinthProfileSlope = atand((500 - 50) / plinthDist) %#ok<NOPTS>
% 
% 
% % 
% % 
% % % figure(4)
% % % plot(Ys,atand(gradient(swath,dy)))
% % 
% % % 
% % % figure(5)
% % % clf
% % % plot(Xs,gradient(gradient(topof(cliffedgepos-25,:),dx),dx),'r')
% % % hold on
% % % plot(Xs,gradient(gradient(topof(cliffedgepos+25,:),dx),dx),'g')
% % % hold on
% % % plot(Xs,gradient(gradient(topof(cliffedgepos+50,:),dx),dx),'b')
% % % hold on
% % % plot(Xs,gradient(gradient(topof(cliffedgepos+75,:),dx),dx),'k')
% % 
% figure(6)
% plot(TIMEtrackVol(TIMEtrackVol > 0),-FLUVtrackVol(TIMEtrackVol > 0),'g')
% hold on
